### ISSUE TITLE
'true' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by scholtz** [erdtman/aes-ccm#15]
When i run `npm install aes-ccm --save` it says `'true' is not recognized as an internal or external command`

Does not install

I have latest packages installed.. The installation is not type safe perhaps?

**Comment by raziel057** [comment]
Hi I have the same issue when trying to install on Windows. Are you also installing on Windows env?

**Comment by raziel057** [comment]
It's related to https://github.com/particle-iot/node-aes-ccm/issues/3

**Comment by raziel057** [comment]
I confirm it works on Linux but not on Windows

**Comment by scholtz** [comment]
I confirm I use VS code in windows environment

**Comment by raziel057** [comment]
As a workarround I've done this:
```
npm install -ignore-scripts
```
Then modify the ``node_modules\aes-ccm\package.json``:

I just removed the ``preinstall: true`` from "scripts": section

And then run:
```
npm rebuild aes-ccm
```

**Comment by raziel057** [comment]
I just created a PR here: https://github.com/erdtman/aes-ccm/pull/16

**Comment by scholtz** [comment]
Great, it would be nice also to increase the version and publish to npm

**Comment by erdtman** [comment]
This should not be resolved and available in the latest release.

Thank you @raziel057 for the fix!
