### ISSUE TITLE
node-pre-gyp support

### ISSUE THREAD

**Issue by johannespfeiffer** [erdtman/aes-ccm#2]
Hi,

any chance of adding support for node-pre-gyp and provide pre-build binaries? see https://www.npmjs.com/package/node-pre-gyp
E.g. when using this npm inside of a docker-container it requires us to provide a full (temp.) build-chain. It also has some complications during development with docker e.g. when mounting node_modules from a different host platform etc.

Kind regards
Joe

**Comment by erdtman** [comment]
I could probably do that, I would have to read up on how to do that though.

If you have time and knowledge I would also accept to merge a PR from you.

**Comment by johannespfeiffer** [comment]
Sure, please see https://github.com/erdtman/aes-ccm/pull/3

**Comment by erdtman** [comment]
Big thank you for both PRs, after some minor issues I have managed to build the release with the docker container.

Please verify that the release looks good to you?

Thoughts on building the release with travis?

**Comment by johannespfeiffer** [comment]
Thank you for accepting the PRs. Unfortunately we switched to node 11 in the meantime, so we would need another binary. I have added an additional build service and as you suggested added the build to travis. (please see PR #6)
You would need to setup the NODE_PRE_GYP_GITHUB_TOKEN env inside of travis (More options/ Settings / Environment Variables) - be sure that the "Display value in build log" is disabled.

**Comment by erdtman** [comment]
Once again thanks for the PR, just did the build. Will look into Travis soon (thanks for the hints)

**Comment by erdtman** [comment]
done

**Comment by erdtman** [comment]
Please check that it all works

**Comment by johannespfeiffer** [comment]
Works like a charm! Thank you.
